import { GlyfChart, GlyfProvider, useGlyfClient } from "@glyf/react";

const bundleUrl = "/glyf/product_analytics/bundle.json";

export function App() {
  return (
    <GlyfProvider
      bundleUrl={bundleUrl}
      loading={<ShellState title="Loading analytics bundle" />}
      error={(error) => <ShellState title="Could not load analytics" detail={error.message} />}
    >
      <StartupDashboard />
    </GlyfProvider>
  );
}

function StartupDashboard() {
  const client = useGlyfClient();
  const charts = client.listCharts();
  const dashboards = client.listDashboards();
  const generatedAt = client.bundle.generated_at
    ? new Intl.DateTimeFormat("en", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date(client.bundle.generated_at))
    : "latest build";

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <a className="brand" href="/">
          <span className="brand-mark">G</span>
          <span>
            <strong>Northstar</strong>
            <small>Growth OS</small>
          </span>
        </a>

        <nav className="nav-list" aria-label="Demo navigation">
          <a className="active" href="#overview">Overview</a>
          <a href="#activation">Activation</a>
          <a href="#retention">Retention</a>
          <a href="#reports">Reports</a>
        </nav>

        <div className="bundle-card">
          <span>Glyf bundle</span>
          <strong>{client.bundle.project ?? "product_analytics"}</strong>
          <small>{charts.length} charts loaded from static artifacts</small>
        </div>
      </aside>

      <section className="workspace">
        <header className="topbar">
          <div>
            <p className="eyebrow">Embedded analytics demo</p>
            <h1>Product growth command center</h1>
          </div>
          <div className="topbar-actions">
            <a href={bundleUrl}>bundle.json</a>
            <a href="/glyf/product_analytics/dashboards/product.html">open glyf output</a>
          </div>
        </header>

        <section className="hero-panel" id="overview">
          <div>
            <p className="eyebrow">Live from Glyf artifacts</p>
            <h2>Analytics shipped as static build output, embedded inside a React app.</h2>
            <p>
              This page is not generated by Glyf. It is a product-style React UI
              loading Glyf chart artifacts by name from a public bundle manifest.
            </p>
          </div>
          <div className="hero-metrics">
            <Metric label="Charts" value={charts.length.toString()} />
            <Metric label="Dashboards" value={dashboards.length.toString()} />
            <Metric label="Refreshed" value={generatedAt} />
          </div>
        </section>

        <section className="metric-row" aria-label="Product metrics">
          <Metric label="Activated accounts" value="3,420" trend="+12.8%" />
          <Metric label="Session depth" value="4.7" trend="+0.6" />
          <Metric label="Enterprise mix" value="28%" trend="+4.1%" />
        </section>

        <section className="chart-grid" id="activation">
          <ChartCard
            name="activation_by_plan"
            label="Activation by plan"
            note="Rendered from exported Glyf SVG artifacts."
          />
          <ChartCard
            name="activation_rate_by_plan"
            label="Activation rate"
            note="The React app asks the bundle where this chart lives."
          />
          <ChartCard
            name="active_users"
            label="Active users"
            note="No BI server is required for this embedded view."
          />
          <ChartCard
            name="sessions_by_plan"
            label="Sessions by plan"
            note="The source data pipeline owns the chart definition."
          />
        </section>
      </section>
    </main>
  );
}

function ChartCard({ name, label, note }: { name: string; label: string; note: string }) {
  return (
    <article className="chart-card">
      <div className="card-heading">
        <div>
          <p className="eyebrow">{label}</p>
          <h3>{name}</h3>
        </div>
        <span>glyf</span>
      </div>
      <GlyfChart
        name={name}
        showTitle={false}
        className="glyf-chart"
        imageClassName="chart-image"
        fallback={<div className="missing-chart">Missing chart: {name}</div>}
      />
      <p>{note}</p>
    </article>
  );
}

function Metric({ label, value, trend }: { label: string; value: string; trend?: string }) {
  return (
    <article className="metric-card">
      <span>{label}</span>
      <strong>{value}</strong>
      {trend ? <small>{trend}</small> : null}
    </article>
  );
}

function ShellState({ title, detail }: { title: string; detail?: string }) {
  return (
    <main className="state-shell">
      <div className="brand-mark">G</div>
      <h1>{title}</h1>
      {detail ? <p>{detail}</p> : <p>Fetching the Glyf bundle manifest.</p>}
    </main>
  );
}
